java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw18.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/blackcod/2010/blackcod-nsw19.xml
