---
title: "R Notebook"
output: html_notebook
---

Packages
```{r, include=FALSE}
require(tidyverse)
require(car)
require(MASS)
require(lmerTest)
require(lme4)
require(lsmeans)
library(maps)
library(mapdata)
```


Study site and station locations
```{r}
map("worldHires", "Australia", xlim=c(140,160), ylim=c(-35,-20), col="gray90", fill=TRUE)
```

Read in data
```{r}
data.measure <- read_csv("../../data/ichthyoplankton-measurements.csv")
data.tow <- read_csv("../../data/ichthyoplankton-tow.csv")

# Select relevant columns
data.measure <- filter(data.measure, family != "bothid" & family != "triglid")
data.measure <- filter(data.measure, is.na(not_calibrated), is.na(damaged))
data.measure <- dplyr::select(data.measure, -subgroup, -photo_id, -damaged, -not_calibrated)

# Create factors (tibble does not import as factors)
data.measure$stage <- factor(data.measure$stage, levels = c("PRE", "FLE", "POS"))
data.measure$family <- as.factor(data.measure$family)
data.measure$net <- as.factor(data.measure$net)
data.measure$depth <- as.factor(data.measure$depth)
data.measure$preservation_method <- as.factor(data.measure$preservation_method)
data.measure$feature <- as.factor(data.measure$feature)
data.measure$location <- as.factor(data.measure$location)
data.measure$station <- as.factor(data.measure$station)
data.measure$site <- as.factor(data.measure$site)
data.tow$net <- as.factor(data.tow$net_number)
data.tow$feature <- as.factor(data.tow$feature)
data.tow$feature_name <- as.factor(data.tow$feature_name)
data.tow$location <- as.factor(data.tow$location)
data.tow$site <- as.factor(data.tow$site)
data.tow$station <- as.factor(data.tow$station)

data.measure <- mutate(data.measure, total_length = standard_length + caudal_fin_length)
```


Generate table of fish data
```{r}
summarize(group_by(data.measure,family,stage), count=n())
summarize(group_by(data.measure,family), count=n())
summarize(group_by(data.measure,family), avg_length=mean(total_length), sd_length=sd(total_length))
summarize(group_by(data.measure), count=n())
```


Check for correlations between dissolved oxygen and cholophyll fluroescne
```{r}
data.environment <- select(data.tow, temperature, salinity, chlorophyll_fluorescence, oxygen)
correlate(data.environment)
```

