---
title: "Theoretical chapter - nMDS analysis"
output: html_notebook
---

Packages required
```{r, include=FALSE}
library(tidyverse)
library(vegan)
library(lme4)
library(ggdendro)
library(ggrepel)
library(ggvegan)
library(cowplot)
library(FactoMineR)
library(factoextra)
library(RColorBrewer)
source("theoretical-functions.R")
```

Load data
```{r,include=FALSE}
load(file="phase1.rda")
load(file="phase2.rda")
load(file="phase3.rda")
load(file="nmds.rda")
```

Create community matrices
```{r}
phase1.reefs.community_matrix <- get_community_matrix(phase1.reefs.data,TRUE)
phase1.regions.community_matrix <- get_community_matrix(phase1.regions.data,FALSE)[,-18]
phase2.reefs.community_matrix <- get_community_matrix(phase2.reefs.data,TRUE)
phase2.regions.community_matrix <- get_community_matrix(phase2.regions.data,FALSE)[,-18]
phase3.reefs.community_matrix <- get_community_matrix(phase3.reefs.data,TRUE)
phase3.regions.community_matrix <- get_community_matrix(phase3.regions.data,FALSE)[,-18]
reefs.community_matrix <- get_community_matrix(reefs.data,TRUE)
regions.community_matrix <- get_community_matrix(regions.data,FALSE)[,-18]
```

Labels for the data
```{r}
model <- c("passive-surface","passive","dvm","ovm","ohs-surface","ohs","dvm+ovm+ohs","ovm+ohs","dvm+ovm","dvm+ohs","pomacentridae","labridae","mullidae","scaridae","scorpaenidae","serranidae","synodontidae","stage","timestep","daily")
scenarios <- c("behaviour","behaviour","behaviour","behaviour","behaviour","behaviour","behaviour","behaviour","behaviour","behaviour","ovm-strategy","ovm-strategy","ovm-strategy","ovm-strategy","ovm-strategy","ovm-strategy","ovm-strategy","ovm-method","ovm-method","ovm-method")
regions <- c("Tweed","Byron","Ballina","Yamba","Solitary Is","Nambucca","Pt Macquarie","Crowdy Bay","Pt Stephens","Newcastle","Sydney","Wollongong","Jervis Bay","Ulladulla","Batemans","Merimbula","Eden")
theoretical <- data.frame(model,scenarios)
```


NNDS using all reefs (or regions)
```{r}
#reefs <- colnames(passive.conn.regions)[-18:-19]

data <- as_tibble(passive.surface.conn.regions/(passive.surface.conn.regions+1))
data$sites <- regions
data$behaviour <- rep(c("passive-surface"))
data.passive <- as_tibble(passive.conn.regions/(passive.surface.conn.regions[,-18]+1))
data.passive$sites <- regions
data.passive$behaviour <- rep(c("passive"))
data.diel <- as_tibble(diel.conn.regions/(passive.surface.conn.regions[,-18]+1))
data.diel$sites <- regions
data.diel$behaviour <- rep(c("dvm"))
data.ovm <- as_tibble(ovm.conn.regions/(passive.surface.conn.regions[,-18]+1))
data.ovm$sites <- regions
data.ovm$behaviour <- rep(c("ovm"))
data.orientate.surface <- as_tibble(orientate.surface.conn.regions/(passive.surface.conn.regions[,-18] +1))
data.orientate.surface$sites <- regions
data.orientate.surface$behaviour <- rep(c("ohs-surface"))
data.orientate <- as_tibble(orientate.conn.regions/(passive.surface.conn.regions[,-18] +1))
data.orientate$sites <- regions
data.orientate$behaviour <- rep(c("ohs"))
data.ovm.orientate <- as_tibble(ovm.orientate.conn.regions/(passive.surface.conn.regions[,-18]+1))
data.ovm.orientate$sites <- regions
data.ovm.orientate$behaviour <- rep(c("ovm+ohs"))
data.diel.ovm.orientate <- as_tibble(diel.ovm.orientate.conn.regions/(passive.surface.conn.regions[,-18]+1))
data.diel.ovm.orientate$sites <- regions
data.diel.ovm.orientate$behaviour <- rep(c("dvm+ovm+ohs"))
data.diel.orientate <- as_tibble(diel.orientate.conn.regions/(passive.surface.conn.regions[,-18]+1))
data.diel.orientate$sites <- regions
data.diel.orientate$behaviour <- rep(c("dvm+ohs"))
data.diel.ovm <- as_tibble(diel.ovm.conn.regions/(passive.surface.conn.regions[,-18]+1))
data.diel.ovm$sites <- regions
data.diel.ovm$behaviour <- rep(c("dvm+ovm"))

phase1.community <- data %>% full_join(data.passive) %>% full_join(data.diel) %>% full_join(data.orientate) %>% full_join(data.orientate.surface) %>% full_join(data.ovm) %>% full_join(data.ovm.orientate) %>% full_join(data.diel.ovm) %>% full_join(data.diel.ovm.orientate) %>% full_join(data.diel.orientate)



phase1.community_matrix <- dplyr::select(phase1.community, -behaviour, -sites)
phase1.community_matrix[is.na(phase1.community_matrix)] <- 0

phase1.nmds <- metaMDS(phase1.community_matrix,distance="bray", k=3, trymax=500)
#plot(nmds)
coul = brewer.pal(10, "Set1") 
coul = colorRampPalette(coul)(17)

MDS_xy <- data.frame(phase1.nmds$points)
MDS_xy$behaviour <- phase1.community$behaviour
MDS_xy$sites <- factor(phase1.community$sites, levels=regions)
phase1.nmds.plot <- ggplot(MDS_xy, aes(MDS1, MDS2, colour=behaviour, group=sites))  + theme_bw() + theme(legend.position = "right") + guides(fill=guide_legend(title.position = "top")) + scale_color_manual(name="Region", values = coul) + geom_text(aes(label=sites),check_overlap = F) #scale_shape_manual(name="Behaviour",values=c(3,4,7,8,15,19,17,18,11,14)) 
#+geom_polygon(aes(fill=sites))
ggsave("../../figs/phase1-all-nmds.png",phase1.nmds.plot, scale=1.2)
#save_plot("../../figs/phase1-all-nmds.png",phase1.nmds.plot,base_aspect_ratio = 3.2)

phase1.adonis <- adonis(phase1.community_matrix ~ sites, phase1.community, perm=200)
phase1.adonis
phase1.adonis <- adonis(phase1.community_matrix ~ behaviour, phase1.community, perm=200)
phase1.adonis

phase1.mod <- with(phase1.community, betadisper(vegdist(phase1.community_matrix,"bray"), behaviour))

phase1.dist <- vegdist(phase1.community_matrix,"bray")
phase1.anosim <- anosim(phase1.dist, phase1.community$behaviour)
summary(phase1.anosim)

phase1.community$diversity <- vegan::diversity(phase1.community_matrix)
phase1.community$richness <- rowSums( phase1.community_matrix != 0)

ggplot(phase1.community, aes(behaviour, diversity)) + stat_summary(fun.data = min.mean.sd.max, geom = "boxplot")
ggplot(phase1.community, aes(behaviour, richness)) + stat_summary(fun.data = min.mean.sd.max, geom = "boxplot")
phase1.community$behaviour <- factor(phase1.community$behaviour)
#phase1.regions <- rep(c(paste("nsw",1:17, sep="")),7)
#phase2.sr <- add_column(phase2.sr, regions = phase2.regions)
phase1.lme.diversity <- lme(diversity ~ behaviour , random = ~1 | sites/behaviour, data = phase1.community)
anova(phase1.lme.diversity)
summary(glht(phase1.lme.diversity, linfct=mcp(behaviour="Tukey")))
lets <- cld(glht(phase1.lme.diversity, linfct=mcp(behaviour="Tukey")))


#phase1.mva.model <- manyglm(phase1.mva~phase1.regions.mva$behaviour)
#anova(phase1.mva.model)
```


NNDS using all reefs (or regions) for fish
```{r}
reefs <- c("Tweed","Byron","Ballina","Yamba","Solitary Is","Nambucca","Pt Macquarie","Crowdy Bay","Pt Stephens","Newcastle","Sydney","Wollongong","Jervis Bat","Ulladulla","Batemans","Merimbula","Eden")
data.labrid <- as_tibble(ovm.labrid.conn.regions/(ovm.conn.regions+1))
data.labrid$sites <- reefs
data.labrid$fish <- rep(c("labridae"))
data.mullid <- as_tibble(ovm.mullid.conn.regions[,-18]/(ovm.conn.regions+1))
data.mullid$sites <- reefs
data.mullid$fish <- rep(c("mullidae"))
data.pomacentrid <- as_tibble(ovm.conn.regions/(ovm.conn.regions+1))
data.pomacentrid$sites <- reefs
data.pomacentrid$fish <- rep(c("pomacentridae"))
data.scarid <- as_tibble(ovm.scarid.conn.regions/(ovm.conn.regions+1))
data.scarid$sites <- reefs
data.scarid$fish <- rep(c("scaridae"))
data.synodontid <- as_tibble(ovm.synodontid.conn.regions/(ovm.conn.regions+1))
data.synodontid$sites <- reefs
data.synodontid$fish <- rep(c("synodontidae"))
data.scorpaenid <- as_tibble(ovm.scorpaenid.conn.regions/(ovm.conn.regions+1))
data.scorpaenid$sites <- reefs
data.scorpaenid$fish <- rep(c("scorpaenidae"))
data.serranid <- as_tibble(ovm.serranid.conn.regions/(ovm.conn.regions+1))
data.serranid$sites <- reefs
data.serranid$fish <- rep(c("serranidae"))

phase2.community <- data.labrid %>% full_join(data.serranid) %>% full_join(data.pomacentrid) %>% full_join(data.synodontid) %>% full_join(data.mullid) %>% full_join(data.scorpaenid) %>% full_join(data.scarid)
phase2.community$fish <- factor(phase2.community$fish)
phase2.community_matrix <- dplyr::select(phase2.community, -fish, -sites)
phase2.community_matrix[is.na(phase2.community_matrix)] <- 0

phase2.nmds <- metaMDS(phase2.community_matrix,distance="bray", k=2, trymax=100)
#plot(nmds)

MDS_xy <- data.frame(phase2.nmds$points)
MDS_xy$fish <- phase2.community$fish
MDS_xy$sites <- factor(phase2.community$sites, levels=reefs)
phase2.nmds.plot <- ggplot(MDS_xy, aes(MDS1, MDS2, colour=sites, shape=fish, group=sites, label=sites))  + theme_bw() + theme(legend.position = "right") + guides(fill=guide_legend(title.position = "top")) + scale_color_manual(name="Region", values = coul) + geom_point(size=3) + scale_shape_manual(name="OVM Strategy",values=c(3,4,7,8,15,16,17,18)) 
#+geom_polygon(aes(fill=sites))
ggsave("../../figs/phase2-all-nmds.png",phase2.nmds.plot, scale=1.2)

phase2.adonis <- adonis(phase2.community_matrix ~ fish, phase2.community, perm=200)
phase2.adonis

mod <- with(phase2.community, betadisper(vegdist(phase2.community_matrix,"bray"), fish))
plot(mod)

phase2.dist <- vegdist(phase2.community_matrix,"bray")
phase2.anosim <- anosim(phase2.dist, phase2.community$sites)
summary(phase2.anosim)

phase2.community$diversity <- vegan::diversity(phase2.community_matrix)
phase2.community$richness <- rowSums( phase2.community_matrix != 0)
ggplot(phase2.community, aes(fish, diversity)) + stat_summary(fun.data = min.mean.sd.max, geom = "boxplot")
ggplot(phase2.community, aes(fish, richness)) + stat_summary(fun.data = min.mean.sd.max, geom = "boxplot")

phase2.lme.diversity <- lme(diversity ~ fish , random = ~1 | sites/fish, data = phase2.community)
anova(phase2.lme.diversity)

phase2.lme.richness <- lme(richness ~ fish , random = ~1 | sites/fish, data = phase2.community)
anova(phase2.lme.richness)

#phase2.mva.model <- manyglm(phase2.mva~phase2.regions.mva$fish)
#anova(phase2.mva.model)
```

NNDS using all reefs (or regions) for implementatinos
```{r}
reefs <- c("Tweed","Byron","Ballina","Yamba","Solitary Is","Nambucca","Pt Macquarie","Crowdy Bay","Pt Stephens","Newcastle","Sydney","Wollongong","Jervis Bay","Ulladulla","Batemans","Merimbula","Eden")
data.timestep <- as_tibble(ovm.timestep.conn.regions/(ovm.conn.regions+1))
data.timestep$sites <- reefs
data.timestep$methods <- rep(c("timestep"))
data.daily <- as_tibble(ovm.daily.conn.regions/(ovm.conn.regions+1))
data.daily$sites <- reefs
data.daily$methods <- rep(c("daily"))
data.stage <- as_tibble(ovm.conn.regions/(ovm.conn.regions+1))
data.stage$sites <- reefs
data.stage$methods<- rep(c("stage"))

phase3.community <- data.timestep %>% full_join(data.daily) %>% full_join(data.stage) 
phase3.community_matrix <- dplyr::select(phase3.community, -methods, -sites)
phase3.community_matrix[is.na(phase3.community_matrix)] <- 0

phase3.nmds <- metaMDS(phase3.community_matrix,distance="bray", k=2, trymax=100)
#plot(nmds)

MDS_xy <- data.frame(phase3.nmds$points)
MDS_xy$methods <- phase3.community$methods
MDS_xy$sites <- factor(phase3.community$sites, levels=reefs)
phase3.nmds.plot <- ggplot(MDS_xy, aes(MDS1, MDS2, colour=sites, shape=methods, group=sites, label=sites))  + theme_bw() + theme(legend.position = "right") + guides(fill=guide_legend(title.position = "top")) + scale_color_manual(name="Region", values = coul) + geom_point(size=3) + scale_shape_manual(name="OVM Method",values=c(15,16,17)) 
#+geom_polygon(aes(fill=sites))
ggsave("../../figs/phase3-all-nmds.png",phase3.nmds.plot)
#save_plot("../../figs/phase3-all-nmds.png",phase3.nmds.plot)

phase3.adonis <- adonis(phase3.community_matrix ~ methods, phase3.community, perm=200)
phase3.adonis

mod <- with(phase3.community, betadisper(vegdist(phase3.community_matrix,"bray"), methods))

phase3.dist <- vegdist(phase3.community_matrix,"bray")
phase3.anosim <- anosim(phase3.dist, phase3.community$sites)
summary(phase3.anosim)

phase3.community$diversity <- vegan::diversity(phase3.community_matrix)
phase3.community$richness <- rowSums( phase3.community_matrix != 0)
ggplot(phase3.community, aes(methods, diversity)) + stat_summary(fun.data = min.mean.sd.max, geom = "boxplot") + geom_jitter(position=position_jitter(width=.2), size=3)
ggplot(phase3.community, aes(methods, richness)) + stat_summary(fun.data = min.mean.sd.max, geom = "boxplot")

phase3.community$methods <- factor(phase3.community$methods)

phase3.lme.diversity <- lme(diversity ~ methods , random = ~1 | sites/methods, data = phase3.community)
anova(phase3.lme.diversity)
summary(glht(phase3.lme.diversity, linfct=mcp(methods="Tukey")))
cld(glht(phase3.lme.diversity, linfct=mcp(methods="Tukey")))

phase3.lme.richness <- lme(richness ~ methods , random = ~1 | sites/methods, data = phase3.community)
anova(phase3.lme.richness)

#phase3.mva.model <- manyglm(phase3.mva~phase3.regions.mva$impl)
#anova(phase3.mva.model)
```



```{r}

#models <- c("passive","dvm","ovm","ohs","dvm+ovm+ohs","ovm+ohs","dvm+ovm","dvm+ohs")
regions <- c("Tweed","Byron","Ballina","Yamba","Solitary Is","Nambucca","Pt Macquarie","Crowdy Bay","Pt Stephens","Newcastle","Sydney","Wollongong","Jervis Bay","Ulladulla","Batemans","Merimbula","Eden", "Victoria","Lord Howe Is")
#rownames(phase1.regions.community_matrix) <- models
colnames(regions.community_matrix) <- regions
all.ca <- CA(regions.community_matrix, graph=FALSE)
summary(all.ca)
fviz_screeplot(all.ca, addlabels=TRUE)
all.biplot <- fviz_ca_biplot(all.ca, map="colgreen", arrow=c(FALSE,TRUE), repel=TRUE, title = "") + theme_classic()
fviz_ca_row(all.ca, repel=TRUE)
fviz_ca_col(all.ca, repel=TRUE)
row <- get_ca_row(all.ca)
row$contrib
#ggsave("../../figs/phase1-ca.png",phase1.biplot)

regions.bray = vegdist(regions.community_matrix, "bray")
mds <- wcmdscale(regions.bray, k=2)
ca <- cca(regions.community_matrix)
all.ca.data <- fortify(ca)
all.ca.data <- filter(all.ca.data, Score=="sites")
all.ca.data$scenario <- scenarios
all.ca.data$model <- model
plot(mds)

all.nmds.plot <- ggplot(all.ca.data, aes(CA1, CA2, colour=scenario, group=scenario, label=model))  + theme_classic() + theme(legend.position = "right") + geom_point(size=3) + geom_text_repel(size=4) + scale_colour_discrete(name="Scenario")
ggsave("../../figs/all-nmds.png",all.nmds.plot)
#+geom_polygon(aes(fill=sites))

```


```{r}

phase1.regions.cca <- cca(sqrt(phase1.regions.community_matrix))
layout(matrix(1:2,1,2,byrow = TRUE))
plot(phase1.regions.cca, display="sites", main="Behaviours", scaling="sites")
#text(phase1.regions.cca, display="sites", scaling="sites")
plot(phase1.regions.cca, display="species", main="Regions", scaling="species",cex=2)
#text(phase1.regions.cca, display="species", scaling="species")

phase1.regions.cca <- cca(sqrt(phase1.regions.community_matrix))
plot(phase1.regions.cca,scaling=3)
phase2.regions.cca <- cca(sqrt(phase2.regions.community_matrix))
plot(phase2.regions.cca,scaling=3)
phase3.regions.cca <- cca(sqrt(phase3.regions.community_matrix))
plot(phase3.regions.cca,scaling=2)

phase1.reefs.cca <- cca(sqrt(phase1.reefs.community_matrix))
plot(phase1.reefs.cca, scaling=2)
```


```{r}




# PCA
jpeg('../../figs/regions-phase1-pca.jpg')
phase1.regions.rda <- rda(phase1.regions.community_matrix, scale = TRUE)
biplot(phase1.regions.rda, display=c("sites","species"), type=c("points","text"))
orditorp(phase1.regions.rda, display="species")
ordilabel(phase1.regions.rda, scaling = 3)
dev.off()

jpeg('../../figs/regions-phase2-pca.jpg')
phase2.regions.rda <- rda(phase2.regions.community_matrix, scale = TRUE)
biplot(phase2.regions.rda, display=c("sites","species"), type=c("points","text"))
orditorp(phase2.regions.rda, display="species")
ordilabel(phase2.regions.rda, scaling = 3, col="blue",font=1)
dev.off()

jpeg('../../figs/regions-phase3-pca.jpg')
phase3.regions.rda <- rda(phase3.regions.community_matrix, scale = TRUE)
priSpp <- diversity(phase3.regions.community_matrix, index = "invsimpson", MARGIN = 2)
priSite <- diversity(phase3.regions.community_matrix, index = "invsimpson", MARGIN = 1)
#biplot(phase3.regions.rda, display=c("sites","species"), scaling = 3)
plot(phase3.regions.rda, type = "n", scaling = 3)
ordilabel(phase3.regions.rda, display = "sites",priority = priSite, font = 3, fill = "hotpink",
          col = "blue")
ordilabel(phase3.regions.rda, display = "species",priority = priSpp, font = 2)
dev.off()
#orditorp(phase3.regions.rda, display="species")

phase2.regions.rda <- rda(phase2.regions.community_matrix, scale = TRUE)
priSpp <- diversity(phase2.regions.community_matrix, index = "invsimpson", MARGIN = 2)
priSite <- diversity(phase2.regions.community_matrix, index = "invsimpson", MARGIN = 1)
#biplot(phase2.regions.rda, display=c("sites","species"), scaling = 3)
plot(phase2.regions.rda, type = "n", scaling = 3)
ordilabel(phase2.regions.rda, display = "sites",priority = priSite, font = 3, fill = "hotpink",
          col = "blue", scaling = 3)
ordilabel(phase2.regions.rda, display = "species",priority = priSpp, font = 2 ,
          scaling = 3)

```
CA analysis 

```{r}
models <- c("passive-surface","passive","dvm","ovm","ohs-surface","ohs","dvm+ovm+ohs","ovm+ohs","dvm+ovm","dvm+ohs")
regions <- c("Tweed","Byron","Ballina","Yamba","Solitary Is","Nambucca","Pt Macquarie","Crowdy Bay","Pt Stephens","Newcastle","Sydney","Wollongong","Jervis Bat","Ulladulla","Batemans","Merimbula","Eden", "Victoria")
rownames(phase1.regions.community_matrix) <- models
colnames(phase1.regions.community_matrix) <- regions
phase1.ca <- CA(phase1.regions.community_matrix, graph=FALSE)
summary(phase1.ca)
fviz_screeplot(phase1.ca, addlabels=TRUE)
phase1.biplot <- fviz_ca_biplot(phase1.ca, map="colgreen", arrow=c(FALSE,TRUE), repel=TRUE, title = "") + theme_classic()
fviz_ca_row(phase1.ca, repel=TRUE)
fviz_ca_col(phase1.ca, repel=TRUE)
row <- get_ca_row(phase1.ca)
row$contrib
ggsave("../../figs/phase1-ca.png",phase1.biplot)

regions <- c("Tweed","Byron","Ballina","Yamba","Solitary Is","Nambucca","Pt Macquarie","Crowdy Bay","Pt Stephens","Newcastle","Sydney","Wollongong","Jervis Bat","Ulladulla","Batemans","Merimbula","Eden", "Victoria", "Lord Howe Is")
colnames(phase2.regions.community_matrix) <- regions
phase2.ca <- CA(phase2.regions.community_matrix, graph=FALSE)
summary(phase2.ca)
fviz_screeplot(phase2.ca, addlabels=TRUE)
phase2.biplot <- fviz_ca_biplot(phase2.ca, map="colgreen", arrow=c(FALSE,TRUE), repel=TRUE, title = "") + theme_classic()
fviz_ca_row(phase2.ca, repel=TRUE)
fviz_ca_col(phase2.ca, repel=TRUE)
row <- get_ca_row(phase2.ca)
row$contrib
ggsave("../../figs/phase2-ca.png",phase2.biplot)

regions <- c("Tweed","Byron","Ballina","Yamba","Solitary Is","Nambucca","Pt Macquarie","Crowdy Bay","Pt Stephens","Newcastle","Sydney","Wollongong","Jervis Bat","Ulladulla","Batemans","Merimbula","Eden", "Victoria")
colnames(phase3.regions.community_matrix) <- regions
phase3.ca <- CA(phase3.regions.community_matrix, graph=FALSE)
summary(phase3.ca)
fviz_screeplot(phase3.ca, addlabels=TRUE)
phase3.biplot <- fviz_ca_biplot(phase3.ca, map="colgreen", arrow=c(FALSE,TRUE), repel=TRUE, title = "") + theme_classic()
fviz_ca_row(phase3.ca, repel=TRUE)
fviz_ca_col(phase3.ca, repel=TRUE)
row <- get_ca_row(phase3.ca)
row$contrib
ggsave("../../figs/phase3-ca.png",phase3.biplot)

```

Biodiversity index
```{r}
rownames(phase1.regions.community_matrix) <- models
phase1.regions.bray = vegdist(phase1.regions.community_matrix, "bray")
#rownames(phase1.regions.community_matrix) <- models
hist(phase1.regions.bray)
phase1.reefs.cluster <- hclust(phase1.regions.bray, method="average")
phase1.reefs.dendrogram <- as.dendrogram(phase1.reefs.cluster) 
plot(phase1.reefs.cluster, xlab ="Behaviours" , ylab = "Bray-Curtis dissimilarity", hang=-1, cex = 1)
phase1.plot <- ggdendrogram(phase1.reefs.cluster, theme_dendro = FALSE, rotate=TRUE) + theme_classic() + labs(x="Behaviour", y="Bray-Curtis dissimilarity")

phase1.plot
```

Biodiversity index for Phase 2
```{r}

phase2.reefs.bray = vegdist(phase2.regions.community_matrix, "bray")
hist(phase2.reefs.bray)
phase2.reefs.cluster <- hclust(phase2.reefs.bray, method="average")
phase2.reefs.dendrogram <- as.dendrogram(phase2.reefs.cluster) 
plot(phase2.reefs.cluster, xlab ="Behaviours" , ylab = "Bray-Curtis dissimilarity", hang=-1, cex = 1)
phase2.plot <- ggdendrogram(phase2.reefs.cluster, theme_dendro = FALSE, rotate=TRUE) + theme_classic() + labs(x="OVM strategies", y="Bray-Curtis dissimilarity")
phase2.plot
```

Biodiversity index for Phase 3
```{r}
phase3.reefs.data.t <- t(phase3.reefs.data)
names(phase3.reefs.data.t) <- phase3.reefs.data.t[1,]
phase3.reefs.data.t <- phase3.reefs.data.t[-1,]
phase3.reefs.data.t[is.na(phase3.reefs.data.t)] <- 0

# shannons
phase3.reefs.shannon <- vegan::diversity(phase3.reefs.data.t)
phase3.reefs.shannon
#anova(phase3.reefs.shannon)

phase3.reefs.bray = vegdist(phase3.reefs.data.t, "bray")
hist(phase3.reefs.bray)
phase3.reefs.cluster <- hclust(phase3.reefs.bray, method="average")
phase3.reefs.dendrogram <- as.dendrogram(phase3.reefs.cluster) 
plot(phase3.reefs.cluster, xlab ="Behaviours" , ylab = "Bray-Curtis dissimilarity", hang=-1, cex = 1)
phase3.plot <- ggdendrogram(phase3.reefs.cluster, theme_dendro = FALSE, rotate=TRUE) + theme_classic() + labs(x="OVM methods", y="Bray-Curtis dissimilarity")
phase3.plot
```

```{r}
grid <- plot_grid(phase1.plot,phase2.plot, phase3.plot, labels="AUTO", align ="hv")
save_plot("../../figs/cluster.png", grid, ncol=2, nrow=2)
```

MVABUND
```{r}
phase1.regions.mva <- phase1.regions.data %>% rownames_to_column %>% gather(behaviour,value,-settle.region) %>% spread(settle.region,value)
phase1.regions.mva <- phase1.regions.mva[-9,-19]
phase1.regions.mva$behaviour <- factor(phase1.regions.mva$behaviour)
phase1.regions.mva <- japply( phase1.regions.mva, which(sapply(phase1.regions.mva,class)=="character"),as.numeric)
phase1.regions.mva
phase1.mva <- mvabund(phase1.regions.mva[,2:18])

par(mar=c(2,10,2,2)) # adjusts the margins
boxplot(phase1.regions.mva[,2:18],horizontal = TRUE,las=2)
meanvar.plot(phase1.mva)
plot(phase1.mva~phase1.regions.mva$behaviour, height=9,width=9, cex.axis=0.8, cex=0.8)

phase1.mva.model <- manyglm(phase1.mva~phase1.regions.mva$behaviour)
anova(phase1.mva.model)
```

Settlement reef richness
```{r}
rowSums(phase1.reefs.data.t > 0)
rowSums(phase2.reefs.data.t > 0)
rowSums(phase3.reefs.data.t > 0)
```

Metrics graphs
```{r}
model.levels <- c("passive-surface","passive","dvm","ovm","ohs-surface","ohs","dvm+ohs","dvm+ovm","dvm+ovm+ohs","ovm+ohs","pomacentridae","labridae","mullidae","scaridae","scorpaenidae","serranidae","synodontidae","stage","timestep","daily")

metrics1 <- dplyr::select(phase1.community, diversity, richness, behaviour) %>% mutate(scenario = "behaviour")
metrics2 <- dplyr::select(phase2.community, diversity, richness, fish) %>% mutate(scenario = "ovm-strategy")
metrics3 <- dplyr::select(phase3.community, diversity, richness, methods) %>% mutate(scenario = "ovm-methods")
metrics <- metrics1 %>% full_join(metrics2) %>% full_join(metrics3) %>% gather(key="scenarios",value="model", behaviour, fish, methods) %>% filter(model != "NA")

metrics$model <- factor(metrics$model, levels=rev(model.levels))

metrics.plot1 <- ggplot(data=metrics, aes(model, diversity, fill=scenario),na.rm = TRUE) + stat_summary(fun.data = min.mean.sd.max, geom = "boxplot") + coord_flip() + labs(x = "", y="Settlement diversity")+ theme(legend.position = "none") + scale_fill_discrete(name="") +guides(fill=guide_legend(nrow=2,byrow=TRUE))

metrics.plot2 <- ggplot(data=metrics, aes(model, richness, fill=scenario),na.rm = TRUE) + stat_summary(fun.data = min.mean.sd.max, geom = "boxplot") + coord_flip()  + labs(x = "", y="Settlement richness")+ theme(legend.position = "none") + scale_fill_discrete(name="") +guides(fill=guide_legend(nrow=2,byrow=TRUE))

load(file="graph.rda")
connectance.data$model <- factor(connectance.data$model, levels=rev(model.levels))
metrics.plot3 <- ggplot(data=connectance.data, aes(model, connectance, colour=scenario),na.rm = TRUE) + geom_point(size=3) + coord_flip()  + labs(x = "", y="Connectance")+ theme(legend.position = "right") + scale_colour_discrete(name="Scenario")

legend <- get_legend(metrics.plot3)
metrics.plot3a <- metrics.plot3 + theme(legend.position = "none")

metrics.grid <- plot_grid(metrics.plot2,metrics.plot1, metrics.plot3a, labels="AUTO", align ="hv")
metrics.legend <- plot_grid(metrics.grid, legend, rel_widths=c(1,.2))
save_plot("../../figs/settle-metrics.png", metrics.legend, ncol=2, nrow=2)
```

