---
title: "R Notebook"
output: html_notebook
---

```{r}
require(maps)
require(mapdata)
require(rgdal)
require(ggmap)
require(broom)
require(multcompView)
require(cowplot)
require(magick)
library(RColorBrewer)
library(tidyverse)
library(ggthemes)
```


OVM example diagram
```{r}

ovm <- tribble(
  ~stage, ~depth, ~probability,
  "preflexion", 12.5, 60,
  "preflexion", 37.5, 20,
  "preflexion", 62.5, 10,
  "preflexion", 87.5, 10,
  "flexion", 12.5, 25,
  "flexion", 37.5, 38,
  "flexion", 62.5, 30,
  "flexion", 87.5, 7,
  "postflexion", 12.5, 10,
  "postflexion", 37.5, 17,
  "postflexion", 62.5, 43,
  "postflexion", 87.5, 30
)

ovm$stage <- factor(ovm$stage, levels=c("preflexion","flexion","postflexion"), labels=c("Preflexion","Flexion","Postflexion"))
#ovm$depth <- factor(ovm$depth, levels=c("75","50","25","0"))
pal <- canva_pal("Fresh and energetic")(4)
p <- ggplot(ovm, aes(x=stage, y=depth, weight=probability, fill=stage)) +  geom_violin(adjust = .85, trim=FALSE)  + theme_classic()  + labs(y="Depth (m)", x="Ontogenetic stage") + theme(legend.position = "none") + scale_y_reverse(limits=c(100,0)) + scale_fill_manual(values = pal)
ggplot2::ggsave("../../figs/ovm-example.png",p, width=5, height=4)
```

Diel diagram
```{r}

diel <- tribble(
  ~time, ~depth, ~probability,
  "day", 12.5, 10,
  "day", 37.5, 30,
  "day", 62.5, 40,
  "day", 87.5, 20,
  "night", 12.5, 30,
  "night", 37.5, 30,
  "night", 62.5, 30,
  "night", 87.5, 10,
  "night", 0, 10,
)

diel$time <- factor(diel$time, levels=c("day","night"), labels=c("Day","Night"))
#ovm$depth <- factor(ovm$depth, levels=c("75","50","25","0"))
#pal <- canva_pal("Timeless and nautical")(4)
#pal <- canva_pal("Grecian holiday")(4)
pal <- canva_pal("Fresh and energetic")(4)
p <- ggplot(diel, aes(x=time, y=depth, weight=probability, fill=time)) +  geom_violin(adjust = .85, trim=FALSE)  + theme_classic()  + labs(y="Depth (m)", x="Time of day") + theme(legend.position = "none") + scale_y_reverse(limits=c(100,0)) + scale_fill_manual(values = pal)
ggplot2::ggsave("../../figs/diel-example.png",p, width=3, height=4)
```

Study sites diagram
```{r}
#australia <- map("worldHires", "Australia", xlim=c(140,160), ylim=c(-45,-10), col="gray90", fill=TRUE)
#coast = get_openstreetmap(c(147.041,-36.593,159.662,-24.247))
legend.names <- c("1 (Tweed)","2 (Byron)","3 (Ballina)","4 (Yamba)","5 (Solitary Is)","6 (Nambucca)","7 (Pt Macquarie)","8 (Crowdy Bay)","9 (Pt Stephens)","10 (Newcastle)","11 (Sydney)","12 (Wollongong)","13 (Jervis Bay)","14 (Ulladulla)","15 (Batemans)","16 (Merimbula)","17 (Eden)")

centre <- geocode("Sydney, AU")
coast <- get_map(c(lon=151, lat=-33), maptype=c("hybrid"), source="google")
load(file="reefs.rda")
sites <- filter(reefs.id, RELEASE)
australia <- ggmap(coast)

coul = brewer.pal(9, "Set1")
coul = colorRampPalette(coul)(17)
map <- australia + geom_point(aes(x=LON_RELEASE, y=LAT_RELEASE, group=REGION, colour=REGION), size=1.5, data=sites) + theme(legend.position = "right") + labs(x="Longitude", y="Latitude") + scale_color_manual(labels = c("1 (Tweed)","2 (Byron)","3 (Ballina)","4 (Yamba)","5 (Solitary Is)","6 (Nambucca)","7 (Pt Macquarie)","8 (Crowdy Bay)","9 (Pt Stephens)","10 (Newcastle)","11 (Sydney)","12 (Wollongong)","13 (Jervis Bay)","14 (Ulladulla)","15 (Batemans)","16 (Merimbula)","17 (Eden)"), name="Source region", values = coul) 

map


#eddies <- ggdraw() + draw_image("../../figs/nsw-eddies.gif", scale=0.9)
#plot_grid(map,eddies, labels="AUTO")
ggsave("../../figs/release-sites.png", map)
```


OVM proportions diagram

```{r}
ovm.data <- read_csv("../../data/ovm.csv")
ovm.data <- ovm.data %>% gather(key= stage, value=proportion, 4:6)
ovm.data$stage <- factor(ovm.data$stage, levels=c("preflexion","flexion","postflexion"))
ovm.plot <- ggplot(data= ovm.data, aes(x=stage, y=depth, weight=proportion, fill=stage)) + labs(y="Depth (m)", x="Ontogenetic stage") + facet_wrap(~fish, ncol=2, shrink = TRUE) + theme_classic() + scale_fill_brewer(palette="Paired", name="Ontogenetic stage") + theme(legend.position = "right") +scale_y_reverse(limits=c(100,0)) + geom_violin(adjust = .85, trim=FALSE) 
ggsave("../../figs/ovm-strategies.png", ovm.plot)


data.ontogeny$stage.r <- factor(data.ontogeny$stage, levels=c("PRE","FLE","POS"))
data.ontogeny$depth.r <- factor(data.ontogeny$depth, levels=c("75","25","0"))
ggplot(data=data.ontogeny, aes(y=conc.m, x=depth.r, group=stage.r, color=stage.r)) + facet_wrap(~family, scales="free", ncol=4, shrink = TRUE) + stat_summary_bin(fun.y="mean", geom="line", position=position_dodge(width=0.5), show.legend=FALSE) + stat_summary_bin(fun.y="mean", geom="point", position=position_dodge(width=0.5),size=2) + stat_summary(fun.data = "mean_cl_boot", geom = "linerange",position=position_dodge(width=0.5),show.legend = FALSE) + labs(x="Depth (m)", y=expression("Concentration per 1000 "~m^{3})) + theme_classic() + coord_flip() + scale_color_discrete(name="", labels=c("Preflexion","Flexion","Postflexion")) + theme(legend.position = c(0.85,0.15), legend.justification = c(0.3,0)) 
```


