---
title: "Connectivity"
output: html_notebook
---

```{r}
library(ConnMatTools)
library(tidyverse)
library(agricolae)
```

```{r}
load(file="blackcod.rda")
load(file="reefs.rda")
source("applied-functions.R")
```


```{r}
eggs <- 976000
years <- c("2011","2010","2009","2008","2007","2006","2005","2004")
region.names <- c("Tweed","Byron","Ballina","Yamba","Solitary Is","Nambucca","Pt Macquarie","Crowdy Bay","Pt Stephens","Newcastle","Sydney","Wollongong","Jervis Bay","Ulladulla","Batemans Bay","Merimbula","Eden","Lord Howe Is","E&M Reefs")
```


2011 connectivity metrics
```{r}
blackcod.2011.conn.regions <- blackcod.2011.conn.regions[,-20]
blackcod.2011.sr <- selfRecruitment(blackcod.2011.conn.regions/eggs)
blackcod.2011.lr <- localRetention(blackcod.2011.conn.regions/eggs)
blackcod.2011.rlr <- relativeLocalRetention(blackcod.2011.conn.regions/eggs)
blackcod.2011.ss <- settlementSuccess(blackcod.2011.conn.regions/eggs)
```

2010 connectivity metrics
```{r}
blackcod.2010.conn.regions <- blackcod.2010.conn.regions[,-20:-21]
blackcod.2010.sr <- selfRecruitment(blackcod.2010.conn.regions/eggs)
blackcod.2010.lr <- localRetention(blackcod.2010.conn.regions/eggs)
blackcod.2010.rlr <- relativeLocalRetention(blackcod.2010.conn.regions/eggs)
blackcod.2010.ss <- settlementSuccess(blackcod.2010.conn.regions/eggs)
```

2009 connectivity metrics
```{r}
blackcod.2009.conn.regions <- blackcod.2009.conn.regions[,-20:-21]
blackcod.2009.sr <- selfRecruitment(blackcod.2009.conn.regions/eggs)
blackcod.2009.lr <- localRetention(blackcod.2009.conn.regions/eggs)
blackcod.2009.rlr <- relativeLocalRetention(blackcod.2009.conn.regions/eggs)
blackcod.2009.ss <- settlementSuccess(blackcod.2009.conn.regions/eggs)
```

2008 connectivity metrics
```{r}
blackcod.2008.conn.regions <- blackcod.2008.conn.regions[,-20:-21]
blackcod.2008.sr <- selfRecruitment(blackcod.2008.conn.regions/eggs)
blackcod.2008.lr <- localRetention(blackcod.2008.conn.regions/eggs)
blackcod.2008.rlr <- relativeLocalRetention(blackcod.2008.conn.regions/eggs)
blackcod.2008.ss <- settlementSuccess(blackcod.2008.conn.regions/eggs)
```

2007 connectivity metrics
```{r}
blackcod.2007.conn.regions <- blackcod.2007.conn.regions[,-20:-21]
blackcod.2007.sr <- selfRecruitment(blackcod.2007.conn.regions/eggs)
blackcod.2007.lr <- localRetention(blackcod.2007.conn.regions/eggs)
blackcod.2007.rlr <- relativeLocalRetention(blackcod.2007.conn.regions/eggs)
blackcod.2007.ss <- settlementSuccess(blackcod.2007.conn.regions/eggs)
```

2006 connectivity metrics
```{r}
blackcod.2006.conn.regions <- blackcod.2006.conn.regions[,-20:-21]
blackcod.2006.sr <- selfRecruitment(blackcod.2006.conn.regions/eggs)
blackcod.2006.lr <- localRetention(blackcod.2006.conn.regions/eggs)
blackcod.2006.rlr <- relativeLocalRetention(blackcod.2006.conn.regions/eggs)
blackcod.2006.ss <- settlementSuccess(blackcod.2006.conn.regions/eggs)
```

2005 connectivity metrics
```{r}
blackcod.2005.conn.regions <- blackcod.2005.conn.regions[,-20:-21]
blackcod.2005.sr <- selfRecruitment(blackcod.2005.conn.regions/eggs)
blackcod.2005.lr <- localRetention(blackcod.2005.conn.regions/eggs)
blackcod.2005.rlr <- relativeLocalRetention(blackcod.2005.conn.regions/eggs)
blackcod.2005.ss <- settlementSuccess(blackcod.2005.conn.regions/eggs)
```

2004 connectivity metrics
```{r}
blackcod.2004.conn.regions <- blackcod.2004.conn.regions[,-20:-21]
blackcod.2004.sr <- selfRecruitment(blackcod.2004.conn.regions/eggs)
blackcod.2004.lr <- localRetention(blackcod.2004.conn.regions/eggs)
blackcod.2004.rlr <- relativeLocalRetention(blackcod.2004.conn.regions/eggs)
blackcod.2004.ss <- settlementSuccess(blackcod.2004.conn.regions/eggs)
```

Self-recruitment
```{r}
#years <- c("2011","2010","2009","2008","2007","2006")
blackcod.sr <- as.tibble(t(rbind(blackcod.2011.sr, blackcod.2010.sr, blackcod.2009.sr, blackcod.2008.sr,blackcod.2007.sr, blackcod.2006.sr,blackcod.2005.sr,blackcod.2004.sr)))
colnames(blackcod.sr) <- years
blackcod.sr$regions <- colnames(blackcod.2008.conn.regions)
blackcod.sr <- gather(blackcod.sr, year, sr, -regions)
blackcod.sr$year <- as.factor(blackcod.sr$year)
blackcod.sr$regions <- factor(blackcod.sr$regions)
blackcod.sr$desc <- factor(region.names, levels=rev(region.names[order(blackcod.sr$regions)]))
blackcod.sr.plot <- ggplot(data=blackcod.sr, aes(x=desc,y=sr)) + geom_boxplot() + coord_flip() + theme_bw() + labs(x="Source region", y="Self-recruitment")
blackcod.sr.plot.year <- ggplot(data=blackcod.sr, aes(x=year,y=sr)) + stat_summary(fun.data = min.mean.sd.max, geom = "boxplot") + coord_flip() + theme_bw() + labs(x="", y="Self-recruitment")
ggsave("../../figs/blackcod-region-sr.png", blackcod.sr.plot)
```

Settlement success
```{r}

blackcod.ss <- as.tibble(t(rbind(blackcod.2011.ss, blackcod.2010.ss, blackcod.2009.ss, blackcod.2008.ss,blackcod.2007.ss, blackcod.2006.ss,blackcod.2005.ss,blackcod.2004.ss)))
colnames(blackcod.ss) <- years
blackcod.ss$regions <- colnames(blackcod.2008.conn.regions)
blackcod.ss <- gather(blackcod.ss, year, ss, -regions)
blackcod.ss$year <- as.factor(blackcod.ss$year)
blackcod.ss$regions <- as.factor(blackcod.ss$regions)
blackcod.ss$desc <- factor(region.names,levels=rev(region.names[order(blackcod.ss$regions)]))
blackcod.ss.plot <- ggplot(data=blackcod.ss, aes(x=desc,y=ss)) + geom_boxplot() + coord_flip() + theme_bw() + labs(x="Source region", y="Settlement success")
blackcod.ss.plot.year <- ggplot(data=blackcod.ss, aes(x=year,y=ss)) +stat_summary(fun.data = min.mean.sd.max, geom = "boxplot") + theme_bw() + labs(x="Year", y="Settlement success")
ggsave("../../figs/blackcod-region-ss.png",blackcod.ss.plot)
p1 <- ggplot(aes(y = ss, x = year), data = blackcod.ss)
p1 <- p1 + stat_summary(fun.data = min.mean.sd.max, geom = "boxplot") + geom_jitter(position=position_jitter(width=.2), size=3) + ggtitle("Boxplot con media, 95%CI, valore min. e max.") + xlab("Gruppi") + ylab("Valori") + coord_flip() + theme_bw()
```

Local retention
```{r}
#years <- c("2011","2010","2009","2008","2007","2006")
blackcod.lr <- as.tibble(t(rbind(blackcod.2011.lr, blackcod.2010.lr, blackcod.2009.lr, blackcod.2008.lr,blackcod.2007.lr, blackcod.2006.lr, blackcod.2005.lr, blackcod.2004.lr)))
colnames(blackcod.lr) <- years
blackcod.lr$regions <- colnames(blackcod.2008.conn.regions)
blackcod.lr <- gather(blackcod.lr, year, lr, -regions)
blackcod.lr$year <- as.factor(blackcod.lr$year)
blackcod.lr$regions <- as.factor(blackcod.lr$regions)
blackcod.lr$desc <- factor(region.names,levels=rev(region.names[order(blackcod.lr$regions)]))
blackcod.lr.plot <- ggplot(data=blackcod.lr, aes(x=desc,y=lr)) + geom_boxplot() + coord_flip()+ labs(x="", y="Local retention") + theme_bw()
blackcod.lr.plot.year <- ggplot(data=blackcod.lr, aes(x=year,y=lr)) + stat_summary(fun.data = min.mean.sd.max, geom = "boxplot") +  labs(x="", y="Local retention") + theme_bw()
ggsave("../../figs/blackcod-regions-lr.png",blackcod.lr.plot)
```

Relative local retention
```{r}
#years <- c("2011","2010","2009","2008","2007","2006")
blackcod.rlr <- as.tibble(t(rbind(blackcod.2011.rlr, blackcod.2010.rlr, blackcod.2009.rlr, blackcod.2008.rlr,blackcod.2007.rlr, blackcod.2006.rlr, blackcod.2005.rlr, blackcod.2004.rlr)))
colnames(blackcod.rlr) <- years
blackcod.rlr$regions <- colnames(blackcod.2008.conn.regions)
blackcod.rlr <- gather(blackcod.rlr, year, rlr, -regions)
blackcod.rlr$year <- as.factor(blackcod.rlr$year)
blackcod.rlr$regions <- as.factor(blackcod.rlr$regions)
blackcod.rlr$desc <- factor(region.names,levels=rev(region.names[order(blackcod.rlr$regions)]))

blackcod.rlr.plot <- ggplot(data=blackcod.rlr, aes(x=reorder(desc, rlr, FUN=mean),y=rlr)) + geom_boxplot() + coord_flip() + theme_bw() + labs(x="Local retention (%)")
ggsave("../../figs/blackcod-regions-rlr.png", blackcod.rlr.plot)
```

Dispersal kernel
```{r}
blackcod.dk <- as.tibble(cbind(blackcod.2011.dk.regions$mean.distance, blackcod.2010.dk.regions$mean.distance, blackcod.2009.dk.regions$mean.distance, blackcod.2008.dk.regions$mean.distance,blackcod.2007.dk.regions$mean.distance,blackcod.2006.dk.regions$mean.distance,blackcod.2005.dk.regions$mean.distance, 
                   blackcod.2004.dk.regions$mean.distance))
colnames(blackcod.dk) <- years
blackcod.dk$regions <- colnames(blackcod.2008.conn.regions)
blackcod.dk <- gather(blackcod.dk, year, dk, -regions)
blackcod.dk$year <- as.factor(blackcod.dk$year)
blackcod.dk$regions <- as.factor(blackcod.dk$regions)
blackcod.dk$desc <- factor(region.names, levels=rev(region.names[order(blackcod.dk$regions)]))
blackcod.dk.plot <- ggplot(data=blackcod.dk, aes(x=desc,y=dk)) + geom_boxplot() + coord_flip() + theme_bw() + labs(x="", y="Dispersal distance (km)")
blackcod.dk.plot.year <- ggplot(data=blackcod.dk, aes(x=year,y=dk)) + stat_summary(fun.data = min.mean.sd.max, geom = "boxplot") + theme_bw() + labs(x="Year", y="Dispersal distance (km)")
ggsave("../../figs/blackcod-regions-dk.png",blackcod.dk.plot)
```

```{r}

blackcod.metrics.plot <- plot_grid(blackcod.sr.plot, blackcod.lr.plot, blackcod.ss.plot, blackcod.dk.plot, labels = c("A", "B", "C", "D"), ncol = 2)
save_plot("../../figs/region-metrics.png", blackcod.metrics.plot,
          ncol = 2, # we're saving a grid plot of 2 columns
          nrow = 2, # and 2 rows
          base_aspect_ratio = 1.3
          )

blackcod.metrics.plot.year <- plot_grid(blackcod.sr.plot.year, blackcod.lr.plot.year, blackcod.ss.plot.year, blackcod.dk.plot.year, labels = c("A", "B", "C", "D"), ncol = 2)
save_plot("../../figs/year-metrics.png", blackcod.metrics.plot.year,
          ncol = 2, # we're saving a grid plot of 2 columns
          nrow = 2, # and 2 rows
          base_aspect_ratio = 1.3
          )
```

```{r}


```

Statistical tests
```{r}

blackcod.sr.aov <- with(blackcod.sr,
                   aov(sr ~ year +
                       Error(regions / (year)))
)
summary(blackcod.sr.aov)

#Aov.mod <- aov(Y ~ N + V + Error(B/V), data = oats)
blackcod.sr.lme <- lme(sr ~ year , random = ~1 | regions/year, data = blackcod.sr)

#summary(Aov.mod)
anova(blackcod.sr.lme)
summary(glht(blackcod.sr.lme, linfct=mcp(year="Tukey")))
summary(Lme.mod)
summary(glht(Lme.mod, linfct=mcp(year="Tukey")))

blackcod.lr.aov <- with(blackcod.lr,
                   aov(lr ~ year +
                       Error(regions / (year)))
)
summary(blackcod.lr.aov)

blackcod.ss.aov <- with(blackcod.ss,
                   aov(ss ~ year +
                       Error(regions / (year)))
)
summary(blackcod.ss.aov)

blackcod.rlr.aov <- with(blackcod.rlr,
                   aov(rlr ~ year +
                       Error(regions / (year)))
)
summary(blackcod.rlr.aov)

blackcod.dk.aov <- with(blackcod.dk,
                   aov(dk ~ year +
                       Error(regions / (year)))
)
summary(blackcod.dk.aov)

blackcod.sr.lm <- lm(sr ~ year + regions, data=blackcod.sr)
anova(blackcod.sr.lm)
print(SNK.test(aov(blackcod.sr.lm),"year"))


blackcod.lr.lm <- lm(lr ~ year + regions, data=blackcod.lr)
anova(blackcod.lr.lm)
print(SNK.test(aov(blackcod.lr.lm),"year"))
blackcod.ss.lm <- lm(ss ~ year + regions, data=blackcod.ss)
anova(blackcod.ss.lm)
print(SNK.test(aov(blackcod.ss.lm),"year"))
blackcod.dk.lm <- lm(dk ~ year + regions, data=blackcod.dk)
anova(blackcod.dk.lm)
print(SNK.test(aov(blackcod.dk.lm),"year"))
print(SNK.test(aov(blackcod.dk.lm),"regions"))
blackcod.rlr.lm <- lm(rlr ~ year + regions, data=blackcod.rlr)
anova(blackcod.rlr.lm)
print(SNK.test(aov(blackcod.rlr.lm),"year"))
print(SNK.test(aov(blackcod.rlr.lm),"regions"))
```


```{r}
sols.sr <- filter(blackcod.sr, regions=='NSW05')
summary(sols.sr)
sd(sols.sr$sr)

sols.dk <- filter(blackcod.dk, regions=='NSW05')
summary(sols.dk)
sd(sols.dk$dk)

sols.lr <- filter(blackcod.lr, regions=='NSW05')
summary(sols.lr)
sd(sols.lr$lr)

```

```{r}
fish.rock.sr <- filter(blackcod.sr, regions=='NSW06')
summary(fish.rock.sr)
sd(fish.rock.sr$sr)

fish.rock.dk <- filter(blackcod.dk, regions=='NSW06')
summary(fish.rock.dk)
sd(fish.rock.dk$dk)

```


```{r}
pt.stephens.sr <- filter(blackcod.sr, regions=='NSW09')
summary(pt.stephens.sr)
sd(pt.stephens.sr$sr)

pt.stephens.dk <- filter(blackcod.dk, regions=='NSW09')
summary(pt.stephens.dk)
sd(pt.stephens.dk$dk)

```

```{r}
lord.howe.sr <- filter(blackcod.sr, regions=='NSW18')
summary(lord.howe.sr)
sd(lord.howe.sr$sr)

lord.howe.dk <- filter(blackcod.dk, regions=='NSW18')
summary(lord.howe.dk)
sd(lord.howe.dk$dk)

```

```{r}
e.m.sr <- filter(blackcod.sr, regions=='NSW19')
summary(e.m.sr)
sd(e.m.sr$sr)

e.m.dk <- filter(blackcod.dk, regions=='NSW19')
summary(e.m.dk)
sd(e.m.dk$dk)

```