---
title: "Appliedchapter - nMDS analysis"
output: html_notebook
---

Packages required
```{r, include=FALSE}
library(tidyverse)
library(vegan)
library(ggdendro)
library(ggrepel)
library(ggvegan)
library(cowplot)
library(RColorBrewer)
library(FactoMineR)
library(factoextra)
source("applied-functions.R")
```

Load data
```{r,include=FALSE}
load(file="blackcod.rda")
load(file="nmds.rda")
```

Create community matrices
```{r}
regions.data[is.na(regions.data)] <- 0
reefs.data[is.na(reefs.data)] <- 0
reefs.community_matrix <- get_community_matrix(reefs.data,TRUE)
regions.community_matrix <- get_community_matrix(regions.data,FALSE)
```

Labels for the data
```{r}
years <- c("2011","2010","2009","2008","2007","2006","2005","2004")
applied <- data.frame(years)
region.names <- c("Tweed","Byron","Ballina","Yamba","Solitary Is","Nambucca","Pt Macquarie","Crowdy Bay","Pt Stephens","Newcastle","Sydney","Wollongong","Jervis Bay","Ulladulla","Batemans Bay","Merimbula","Eden","Lord Howe Is","EM Reefs")
region.names.numbered <- c("1 Tweed","2 Byron","3 Ballina","4 Yamba","5 Solitary Is","6 Nambucca","7 Pt Macquarie","8 Crowdy Bay","9 Pt Stephens","10 Newcastle","11 Sydney","12 Wollongong","13 Jervis Bay","14 Ulladulla","15 Batemans Bay","16 Merimbula","17 Eden","18 Lord Howe Is","19 EM Reefs")
settle.names <- c("Queensland","Tweed","Byron","Ballina","Yamba","Solitary Is","Nambucca","Pt Macquarie","Crowdy Bay","Pt Stephens","Newcastle","Sydney","Wollongong","Jervis Bay","Ulladulla","Batemans Bay","Merimbula","Eden","Victoria","Lord Howe Is","EM Reefs", "Norfolk Is", "New Zealand")
region.names.known <- c("Solitary Is","Nambucca","Pt Stephens","Lord Howe Is","E&M Reefs")
settle.names.known <- c("Queensland","Tweed","Byron","Ballina","Yamba","Solitary Is","Nambucca","Pt Macquarie","Crowdy Bay","Pt Stephens","Newcastle","Sydney","Wollongong","Jervis Bay","Ulladulla","Batemans Bay","Merimbula","Eden","Lord Howe Is","EM Reefs")
coul = brewer.pal(9, "Set1") 
coul = colorRampPalette(coul)(19)
coul21 = colorRampPalette(coul)(21)
``` 

NMDS for regions using mean total settlement
```{r}

regions.data[is.na(regions.data)] <- 0
regions.data.mean <- regions.data %>% ungroup() %>% gather(year,value,3:10) %>% group_by(source.region, settle.region) %>% summarise(settlers = mean(value)) %>% spread(settle.region, settlers)
regions.data.mean[is.na(regions.data.mean)] <- 0
regions.mean.nmds <- metaMDS(regions.data.mean[,-1],distance="bray", k=2)
regions.mean.nmds.data <- data.frame(regions.mean.nmds$points)
regions.mean.nmds.data$region <- regions.data.mean$source.region
regions.mean.nmds.plot <- ggplot(regions.mean.nmds.data, aes(MDS1, MDS2)) + geom_label_repel(size=3, label=region.names.numbered) + theme_classic() + theme(legend.position = "none") + geom_point(size=3)
regions.mean.nmds$stress
#ggsave("../../figs/mean-settle-nmds.png", regions.mean.nmds.plot)
```

NMDS for years using total settlement
```{r}
years.data <- regions.data %>% ungroup() %>% gather(year,value,3:10) %>% group_by(year, settle.region) %>% summarise(value = sum(value)) 
years.data.mean <- years.data %>% spread(settle.region, value)
years.data.mean[is.na(years.data.mean)] <- 0
years.data.mds <- metaMDS(years.data.mean[,-1],distance="bray", k=2)
MDS_xy <- data.frame(years.data.mds$points)
MDS_xy$year <- years.data.mean$year
year.nmds.plot <- ggplot(MDS_xy, aes(MDS1, MDS2)) + geom_label_repel(size=3, label=rev(years)) + theme_classic() + theme(legend.position = "none") + geom_point(size=3)
years.data.mds$stress
ggsave("../../figs/years-settle-nmds.png", year.nmds.plot)

years.data.cca <- years.data.mean[,-1]
cap <- capscale(years.data.cca ~ year, years.data.mean, distance="bray", metaMDSdist=TRUE, sqrt.dist=TRUE)
plot <- autoplot(cap, legend.position = "none")
ggsave("../../figs/cca-years.png", plot)
```



```{r}
settlement.grid <- plot_grid(regions.mean.nmds.plot,year.nmds.plot, labels="AUTO", align ="h", ncol=2, nrow=1)
save_plot("../../figs/ndms-settlement.png", settlement.grid, ncol=2, nrow=1)
```

Create connectivity matrix heatmaps
```{r}
eggs <- 976000
regions.data.heatmap <- regions.data %>% ungroup() %>% gather(year,value,3:10) %>% group_by(source.region, settle.region) %>% summarise(settlers = mean(value)/eggs)
regions.data.heatmap <- ungroup(regions.data.heatmap)
regions.data.heatmap <- regions.data.heatmap %>% add_row(source.region="NSW19",settle.region="NFI",settlers=0) %>% add_row( source.region="NSW19",settle.region="NZ",settlers=0)
regions.data.heatmap <- group_by(regions.data.heatmap, source.region, settle.region)
regions.data.heatmap$source.region <- factor(regions.data.heatmap$source.region,levels=rev(c("NSW01","NSW02","NSW03","NSW04","NSW05","NSW06","NSW07","NSW08","NSW09","NSW10","NSW11","NSW12","NSW13","NSW14","NSW15","NSW16","NSW17","NSW18","NSW19")))
regions.data.heatmap$settle.region <- factor(regions.data.heatmap$settle.region, levels=c("QLD","NSW01","NSW02","NSW03","NSW04","NSW05","NSW06","NSW07","NSW08","NSW09","NSW10","NSW11","NSW12","NSW13","NSW14","NSW15","NSW16","NSW17","VIC","NSW18","NSW19","NFI","NZ"))
heatmap.plot <- ggplot(regions.data.heatmap, aes(settle.region,source.region)) + geom_tile(aes(fill=sqrt(sqrt(settlers))), colour="white") + scale_fill_gradient(low="white", high="steelblue",name="Proportion settled\n(4th root)") + theme(legend.position = "right", axis.text.x = element_text(angle=330, hjust=0)) + scale_y_discrete(labels=rev(region.names)) + scale_x_discrete(labels=settle.names) +labs(y="Source region",x="Settlement region")
ggsave("../../figs/heatmap-all.png",heatmap.plot, width=9.17, height=5.43, units=c("in"))

regions.data.heatmap.known <- regions.data %>% ungroup() %>% gather(year,value,3:10) %>% group_by(source.region, settle.region) %>% summarise(settlers = mean(value)/eggs)
regions.data.heatmap.known <- ungroup(regions.data.heatmap.known)
regions.data.heatmap.known <- group_by(regions.data.heatmap.known, source.region, settle.region)
regions.data.heatmap.known$source.region <- factor(regions.data.heatmap.known$source.region, levels=rev(c("NSW01","NSW02","NSW03","NSW04","NSW05","NSW06","NSW07","NSW08","NSW09","NSW10","NSW11","NSW12","NSW13","NSW14","NSW15","NSW16","NSW17","NSW18","NSW19")))
regions.data.heatmap.known$settle.region <- factor(regions.data.heatmap.known$settle.region, levels=c("QLD","NSW01","NSW02","NSW03","NSW04","NSW05","NSW06","NSW07","NSW08","NSW09","NSW10","NSW11","NSW12","NSW13","NSW14","NSW15","NSW16","NSW17","VIC","NSW18","NSW19"))
regions.data.heatmap.known <- regions.data.heatmap.known %>% filter(source.region=="NSW05" | source.region=="NSW06" | source.region=="NSW09" | source.region=="NSW18" | source.region=="NSW19")
heatmap.known.plot <- ggplot(regions.data.heatmap.known, aes(settle.region,source.region)) + geom_tile(aes(fill=sqrt(sqrt(settlers))), colour="white") + scale_fill_gradient(low="white", high="steelblue",name="Proportion settled\n(4th root)") + theme(legend.position = "right", axis.text.x = element_text(angle=330, hjust=0)) + scale_y_discrete(labels=rev(region.names.known)) + scale_x_discrete(labels=settle.names.known) +labs(y="Source region",x="Settlement region")
ggsave("../../figs/heatmap-known.png",heatmap.known.plot, width=9.0, height=2.5, units=c("in"))
```

Variation of total settlement
```{r}
cv.names <- c("Tweed","Byron","Ballina","Yamba","Solitary Is","Nambucca","Pt Macquarie","Crowdy Bay","Pt Stephens","Newcastle","Sydney","Wollongong","Jervis Bay","Ulladulla","Batemans Bay","Merimbula","Eden","Lord Howe Is","EM Reefs","Queensland","Victoria")
regions.data.cv <- regions.data %>% ungroup() %>% gather(year,value,3:10) %>% mutate(value=value/eggs)  %>% group_by(settle.region, year) %>% summarise(settlers = sum(value)) %>% summarise(mean = mean(settlers), cv = (sd(settlers)/mean(settlers))*100)
regions.data.cv.plot <- ggplot(regions.data.cv, aes(mean,cv)) + geom_point() + geom_text_repel(size=4, label=cv.names) + theme(legend.position = "none") + labs(x="", y="Coefficient of variation (%)") + xlim(0, 0.016)
#ggsave("../../figs/settlement-cv.png", regions.data.cv.plot, width=8.17, height=7.43, unit=c("in"))

regions.data.cv.known <- regions.data %>% ungroup() %>% gather(year,value,3:10) %>% filter(source.region=="NSW05" | source.region=="NSW06" | source.region=="NSW09" | source.region=="NSW18" | source.region=="NSW19") %>% mutate(value=value/eggs) %>% group_by(settle.region, year) %>% summarise(settlers = sum(value)) %>% summarise(mean = mean(settlers), cv = (sd(settlers)/mean(settlers))*100)
regions.data.cv.known.plot <- ggplot(regions.data.cv.known, aes(mean,cv)) + geom_point() + geom_text_repel(size=4, label=cv.names[-21]) + theme(legend.position = "none") + labs(x="Mean annual larval settlement (Pr)", y="Coefficient of variation (%)") + xlim(0, 0.016)
#ggsave("../../figs/settlement-cv.png", regions.data.cv.known.plot, width=8.17, height=7.43, unit=c("in"))

p <- plot_grid(regions.data.cv.plot,regions.data.cv.known.plot, labels="AUTO", align="v", nrow=2)
save_plot("../../figs/settlement-cv.png", p, base_aspect_ratio = 1.1, scale=2)

regions.data.lm.known <- regions.data %>% ungroup() %>% gather(year,value,3:10) %>% filter(source.region=="NSW05" | source.region=="NSW06" | source.region=="NSW09" | source.region=="NSW18" | source.region=="NSW19") %>% mutate(value=value/eggs) %>% group_by(settle.region, year) %>% summarise(settlers = sum(value))
regions.lm.known <- lm(settlers ~ year + settle.region, data=regions.data.lm.known)
anova(regions.lm.known)
```

NNDS using all regions
```{r}
regions <- colnames(blackcod.2011.conn.regions)
data.2011 <- as_tibble(blackcod.2011.conn.regions)
data.2011$sites <- regions[-20]
data.2011$year <- rep(c("2011"))
data.2010 <- as_tibble(blackcod.2010.conn.regions)
data.2010$sites <- regions[-20]
data.2010$year <- rep(c("2010"))
data.2009 <- as_tibble(blackcod.2009.conn.regions)
data.2009$sites <- regions[-20]
data.2009$year <- rep(c("2009"))
data.2008 <- as_tibble(blackcod.2008.conn.regions)
data.2008$sites <- regions[-20]
data.2008$year <- rep(c("2008"))
data.2007 <- as_tibble(blackcod.2007.conn.regions)
data.2007$sites <- regions[-20]
data.2007$year <- rep(c("2007"))
data.2006 <- as_tibble(blackcod.2006.conn.regions)
data.2006$sites <- regions[-20]
data.2006$year <- rep(c("2006"))
data.2005 <- as_tibble(blackcod.2005.conn.regions)
data.2005$sites <- regions[-20]
data.2005$year <- rep(c("2005"))
data.2004 <- as_tibble(blackcod.2004.conn.regions)
data.2004$sites <- regions[-20]
data.2004$year <- rep(c("2004"))

community <- data.2011 %>% full_join(data.2010) %>% full_join(data.2009) %>% full_join(data.2008) %>% full_join(data.2007) %>% full_join(data.2006) %>% full_join(data.2005) %>% full_join(data.2004)

community_matrix <- dplyr::select(community, -year, -sites)
community_matrix[is.na(community_matrix)] <- 0
#rownames(community_matrix) <- community$year
nmds <- metaMDS(community_matrix,distance="bray", k=2)
#plot(nmds)

MDS_xy <- data.frame(nmds$points)
MDS_xy$year <- community$year
MDS_xy$sites <- community$sites
#color = colorRampPalette(rev(brewer.pal(n = 8, name = "Paired"))(19))
# Classic palette BuPu, with 4 colors
coul = brewer.pal(9, "Set1") 
 
# I can add more tones to this palette :
coul = colorRampPalette(coul)(19)

nmds.plot.years <- ggplot(MDS_xy, aes(MDS1, MDS2, colour=year)) + geom_point(size=4) + theme_bw() + theme(legend.position = "right")   + scale_colour_brewer(name="", palette="Paired")
ggsave("../../figs/nmds-years.png", nmds.plot.years)

nmds.plot.regions <- ggplot(MDS_xy, aes(MDS1, MDS2, colour=sites)) + geom_point(size=2) + theme_classic() + theme(legend.position = "right")   + scale_colour_manual(values = coul, labels=region.names.numbered, name="Source \nregion") + stat_ellipse(type="norm")
ggsave("../../figs/nmds-regions.png", nmds.plot.regions, width=9, height=6, units=c("in"))


adonis(community_matrix ~ sites + year, community, perm=200)

mod <- with(community, betadisper(vegdist(community_matrix,"bray"), year))

```

```{r}
community$diversity <- vegan::diversity(community_matrix)
community$richness <- rowSums(community_matrix != 0)

diversity.lm <- lm(diversity ~ year + sites, data=community)
anova(diversity.lm)
diversity.sites.snk <- SNK.test(aov(diversity.lm),"sites")$group
diversity.sites.snk$site <- rownames(diversity.sites.snk)
diversity.sites.snk <- diversity.sites.snk[order(diversity.sites.snk$site),]
diversity.sites.snk$desc <- region.names.numbered
diversity.years.snk <- SNK.test(aov(diversity.lm),"year")$group
diversity.years.snk$year <- rownames(diversity.years.snk)

richness.lm <- lm(richness ~ year + sites, data=community)
anova(richness.lm)
richness.sites.snk <- SNK.test(aov(richness.lm),"sites")$group
richness.sites.snk$site <- rownames(richness.sites.snk)
richness.sites.snk <- richness.sites.snk[order(richness.sites.snk$site),]
richness.sites.snk$desc <- region.names.numbered
richness.years.snk <- SNK.test(aov(richness.lm),"year")$group
richness.years.snk$year <- rownames(richness.years.snk)

community$sitedesc <- factor(region.names.numbered, levels=rev(region.names.numbered[order(community$sites)]))
community$yeardesc <- factor(years, levels=years[order(community$year)])

sites.diversity <- ggplot(community, aes(sitedesc, diversity)) + stat_summary(fun.data = min.mean.sd.max, geom = "boxplot") + coord_flip() + theme_classic() + labs(x="Source region",y="Settlement diversity")
sites.richness <- ggplot(community, aes(sitedesc, richness)) + stat_summary(fun.data = min.mean.sd.max, geom = "boxplot") + coord_flip() + theme_classic() + labs(x="Source region",y="Settlement richness")
years.diversity <- ggplot(community, aes(year, diversity)) + stat_summary(fun.data = min.mean.sd.max, geom = "boxplot") + coord_flip() + theme_classic() + labs(x="Year", y="Settlement diversity")
years.richness <- ggplot(community, aes(year, richness)) + stat_summary(fun.data = min.mean.sd.max, geom = "boxplot")  + coord_flip() + theme_classic() + labs(x="Year", y="Settlement richness")
p.sites <- plot_grid(sites.richness, sites.diversity,  labels="AUTO", ncol=2,align ="hv")
p.years <- plot_grid(years.richness, years.diversity,  labels="AUTO", ncol=2,align ="hv")
ggsave("../../figs/diversity-regions.png",p.sites, width = 8, height=3)
ggsave("../../figs/diversity-years.png",p.years, width = 8, height=3)
```

```{r}
#behaviour.names <- c("dvm","dvm+ohs","dvm+ovm","dvm+ovm+ohs","ohs","ohs-surface","ovm","ovm+ohs","passive","passive-surface")
data.cca <- as.data.frame(community_matrix)
#phase1.data.cca[is.na(phase1.data.cca)] <- 0
#phase1.dist <- vegdist(phase1.data.cca,"bray")
cap <- capscale(data.cca ~ sites + year, community, dist="bray", metaMDS=TRUE, sqrt.dist = TRUE)

anova(cap)
anova(cap, by = "margin")
#anova(phase1.cap, by = "axis", perm.max=500)
anova(cap, by = "terms", permu=200)

cca <- as.tibble(fortify(cap)) 
cca <- cca %>% filter(Score == "centroids")
cca.years <- cca[20:27,]
cca.years$year <- rev(c("2011","2010","2009","2008","2007","2006","2005","2004"))
cca.sites <- cca[1:19,]
cca.sites$sites <- c("1 Tweed","2 Byron","3 Ballina","4 Yamba","5 Solitary Is","6 Nambucca","7 Pt Macquarie","8 Crowdy Bay","9 Pt Stephens","10 Newcastle","11 Sydney","12 Wollongong","13 Jervis Bay","14 Ulladulla","15 Batemans Bay","16 Merimbula","17 Eden","18 Lord Howe Is","19 EM Reefs")
#mod <- varpart(phase1.community_matrix, ~ sites, ~ behaviour, data = phase1.community)

cca.plot.year <- ggplot(cca.years, aes(CAP1, CAP2))  + theme_classic() + geom_text_repel(aes(label=year)) + geom_point()
cca.plot.sites <- ggplot(cca.sites, aes(CAP1, CAP2))  + theme_classic() + geom_text_repel(aes(label=sites)) + geom_point()

ggsave("../../figs/cap-years.png", cca.plot.year)
ggsave("../../figs/cap-sites.png", cca.plot.sites)

p <- plot_grid(cca.plot.sites,cca.plot.year, labels="AUTO", align="v", nrow=2)
save_plot("../../figs/cap.png", p, base_aspect_ratio = 1.1, scale=2)

```

```{r}
#models <- c("passive","dvm","ovm","ohs","dvm+ovm+ohs","ovm+ohs","dvm+ovm","dvm+ohs")
#rownames(phase1.regions.community_matrix) <- models
colnames(community_matrix) <-  c("Tweed","Byron","Ballina","Yamba","Solitary Is","Nambucca","Pt Macquarie","Crowdy Bay","Pt Stephens","Newcastle","Sydney","Wollongong","Jervis Bay","Ulladulla","Batemans Bay","Merimbula","Eden", "Lord Howe Is","EM Reefs","Victoria","Queensland")
all.ca <- CA(community_matrix, graph=FALSE)
summary(all.ca)
fviz_screeplot(all.ca, addlabels=TRUE)
all.biplot <- fviz_ca_biplot(all.ca, map="colgreen", arrow=c(TRUE,TRUE), repel=TRUE, title = "") + theme_classic()
fviz_ca_row(all.ca, repel=TRUE)
fviz_ca_col(all.ca, repel=TRUE)
row <- get_ca_row(all.ca)
row$contrib
```

