---
title: "R Notebook"
output: html_notebook
---

```{r}
require(tidyverse)
require(maps)
require(mapdata)
require(rgdal)
require(ggmap)
require(OpenStreetMap)
require(broom)
require(multcompView)
require(cowplot)
require(magick)
library(RColorBrewer)
```

Study sites diagram
```{r}
load("reefs.rda")
sites <- filter(reefs.id, !is.na(LON_RELEASE)) %>% mutate(known=ifelse(REGION == 'NSW05' | REGION == 'NSW06' | REGION == 'NSW09' | REGION=='NSW18' | REGION=='NSW19', TRUE, FALSE)) #%>% mutate(mpa=ifelse(REGION=='NSW05))
#sites <- add_column(sites, known=FALSE, mpa=FALSE)

#australia <- map("worldHires", "Australia", xlim=c(140,160), ylim=c(-45,-10), col="gray90", fill=TRUE)
#coast = get_openstreetmap(c(147.041,-36.593,159.662,-24.247))
legend.names <- c("Tweed","Byron","Ballina","Yamba","Solitary Is","Nambucca","Pt Macquarie","Crowdy Bay","Pt Stephens","Newcastle","Sydney","Wollongong","Jervis Bat","Ulladulla","Batemans","Merimbula","Eden","Lord Howe", "EM Reefs")

map <- openmap(c(lat= -27, lon= 149), c(lat= -38, lon= 160), type="osm")
mapLatLon <- openproj(map)
g <- autoplot(mapLatLon)
coul <- brewer.pal(9, "Set1")
coul <- colorRampPalette(coul)(19)
g <- g + geom_point(aes(x=LON_RELEASE, y=LAT_RELEASE, color=factor(REGION), shape=known), size=2, data=sites) + theme(legend.position = "right", legend.text = element_text(size=10)) + labs(x="Longitude", y="Latitude") +
scale_color_manual(labels = c("1 Tweed","2 Byron","3 Ballina","4 Yamba","5 Solitary Is","6 Nambucca","7 Pt Macquarie","8 Crowdy Bay","9 Pt Stephens","10 Newcastle","11 Sydney","12 Wollongong","13 Jervis Bay","14 Ulladulla","15 Batemans","16 Merimbula","17 Eden","18 Lord Howe Is", "19 EM Reefs"), name="Release regions", values = coul) + 
scale_shape_manual(values=c(1, 16), labels=c("Unnown","Known"),name="Sites of\n aggregation") + guides(colour=guide_legend(ncol=1,title.position = "top"),shape=guide_legend(ncol=1,title.position = "top"))
ggplot2::ggsave("../../figs/release-sites.png", g, height=6, width=5, scale=1.5)

#p1 <- ggdraw() + draw_image("../../figs/release-sites.png")
p1 <- ggdraw() + draw_image("../../figs/NSW-marine-protected-area-map.pdf")
p2 <- ggdraw() + draw_image("../../figs/map-te-network_0.jpg")
maps.grid <- plot_grid(p1,p2,labels="AUTO", align="h")
save_plot("../../figs/mpa-locations.png",maps.grid)
```

Trajectories

```{r}
map <- openmap(c(lat= -27, lon= 149), c(lat= -38, lon= 160), type="osm")
mapLatLon <- openproj(map)
g <- autoplot(mapLatLon)


shapefile <- readOGR("../../data/model-output/2004/blackcod-nsw01", "blackcod-nsw01-dispersal")

# Next the shapefile has to be converted to a dataframe for use in ggplot2
shapefile_df <- fortify(shapefile)

# Now the shapefile can be plotted as either a geom_path or a geom_polygon.
# Paths handle clipping better. Polygons can be filled.
# You need the aesthetics long, lat, and group.
map <- ggplot() +
geom_path(data = shapefile_df, 
          aes(x = long, y = lat, group = group),
          color = 'gray', fill = 'white', size = .2)
```

```{r}
p1 <- ggdraw() + draw_image("../../figs/trajectories/coastline.png")
p2 <- ggdraw() + draw_image("../../figs/trajectories/off-shore.png")
trajectories.grid <- plot_grid(p1,p2,labels="AUTO", align="hv")
save_plot("../../figs/trajectories-panel.png",trajectories.grid)
```

Trajectories by year
```{r}

p04 <- ggdraw() + draw_image("../../figs/trajectories/2004.png")
p05 <- ggdraw() + draw_image("../../figs/trajectories/2005.png")
p06 <- ggdraw() + draw_image("../../figs/trajectories/2006.png")
p07 <- ggdraw() + draw_image("../../figs/trajectories/2007.png")
p08 <- ggdraw() + draw_image("../../figs/trajectories/2008.png")
p09 <- ggdraw() + draw_image("../../figs/trajectories/2009.png")
p10 <- ggdraw() + draw_image("../../figs/trajectories/2010.png")
p11 <- ggdraw() + draw_image("../../figs/trajectories/2011.png")
trajectories.grid <- plot_grid(p04,p05,p06,p07,p08,p09,p10,p11,labels=c("2004","2005","2006","2007","2008","2009","2010","2011"), ncol=3, nrow=3, align="vh")
save_plot("../../figs/trajectories-years.png",trajectories.grid, ncol=3, nrow=3)
```

OVM strategy
```{r}
ovm.data <- read_csv("../../data/ovm.csv")
ovm.data <- ovm.data %>% gather(key= stage, value=proportion, 3:5)
ovm.data$stage <- factor(ovm.data$stage, levels=c("preflexion","flexion","postflexion"), labels=c("Preflexion","Flexion","Postflexion"))

pal <- canva_pal("Fresh and energetic")(4)

ovm.plot <- ggplot(ovm.data, aes(x=stage, y=depth, weight=proportion, fill=stage)) +  geom_violin(adjust = .85, trim=FALSE)  + theme_classic() + labs(y="Depth (m)", x="Ontogenetic stage") + theme(legend.position = "none") + scale_y_reverse(limits=c(100,0)) + scale_fill_manual(values = pal)
ggsave("../../figs/ovm.png", ovm.plot, width=4.5, height=4)
```

