---
title: "Graph theory analysis for my theoreticla chapter"
output: html_notebook
---

Packages required
```{r, include=FALSE}
library(igraph)
library(NetIndices)
library(ggdendro)
library(tidyverse)
library(cowplot)
```


Load the data
```{r,include=FALSE}
load(file="blackcod.rda")
load(file="reefs.rda")
load(file="nmds.rda")
```

Graph analysis for regions
```{r}

region.names <- c("1 Tweed","2 Byron","3 Ballina","4 Yamba","5 Solitary Is","6 Nambucca","7 Pt Macquarie","8 Crowdy Bay","9 Pt Stephens","10 Newcastle","11 Sydney","12 Wollongong","13 Jervis Bay","14 Ulladulla","15 Batemans Bay","16 Merimbula","17 Eden","18 Lord Howe Is","19 EM Reefs")
region.names.known <- c("5 Solitary Is","6 Nambucca","9 Pt Stephens","18 Lord Howe Is","19 EM Reefs")

X <- list(blackcod.2011.conn.regions[,-20],blackcod.2010.conn.regions[-20:-21],blackcod.2009.conn.regions[,-20:-21],blackcod.2008.conn.regions[,-20:-21],blackcod.2007.conn.regions[,-20:-21],blackcod.2006.conn.regions[,-20:-21],blackcod.2005.conn.regions[,-20:-21],blackcod.2004.conn.regions[,-20:-21])

Y <- do.call(cbind, X)
Y <- array(Y, dim=c(dim(X[[1]]),length(X)))

data.averages <- apply(Y, c(1,2), mean, na.rm=TRUE)

rownames(data.averages) <- unique(blackcod.2011.regions$settle.region)[-20]
colnames(data.averages) <-  unique(blackcod.2011.regions$settle.region)[-20]

graph <- graph_from_adjacency_matrix(data.averages[,-20], weighted = TRUE)
V(graph)$desc <- region.names
graph.simple <- simplify(graph, remove.loops=T)
E(graph)$width
plot(graph.simple, edge.arrow.size=0.2, edge.curved=0.1, edge.width=E(graph)$weight/500, vertex.label.family="Helvetica", vertex.label.color="black", vertex.label.cex=0.9,vertex.label=region.names, vertex.label.font=2)

plot(graph.simple, edge.arrow.size=0.2, edge.curved=0.1, edge.width=E(graph)$weight/500, vertex.label.family="Helvetica", vertex.label.color="gray40", vertex.label.cex=0.9,vertex.label=region.names, vertex.label.font=2, vertex.shape="none")
```

```{r}
regions.data.graph <- regions.data %>% ungroup() %>% gather(year,value,3:10) %>% group_by(source.region, settle.region) %>% summarise(weight = round(mean(value),0), cv = round((sd(value)/mean(value))*100,0)) %>% filter(settle.region != "VIC" & settle.region != "QLD") %>% replace_na(list(weight = 0, cv= 0))

blackcod.graph.directed <- graph_from_data_frame(regions.data.graph, directed=TRUE)
# regions.data.graph <- regions.data.graph %>% ungroup()
# mean(regions.data.graph$weight)
# regions.data.graph <- regions.data.graph %>% spread(settle.region, weight, fill=0) 
# rownames(regions.data.graph) <- regions.data.graph$source.region
# 
# regions.data.graph <- regions.data.graph[,-1]
# regions.data.graph <- regions.data.graph[,-20:-21]
# blackcod.graph.directed <- graph_from_adjacency_matrix(as.matrix(regions.data.graph), mode=c("directed"), weighted=TRUE)
# blackcod.graph.undirected <- graph_from_adjacency_matrix(as.matrix(regions.data.graph), mode=c("undirected"), weighted=TRUE)

wc <- walktrap.community(blackcod.graph.directed)

png(filename="../../figs/dendo-all-regions.png", width=800, height=800)
plot_dendrogram(wc, mode="hclust", label=region.names, cex=1.5,palette=c("mediumpurple","tomato","turquoise1","limegreen"))
dev.off()

blackcod.graph.directed <- igraph::simplify(blackcod.graph.directed, remove.multiple = FALSE, remove.loops=TRUE)
mean.cut.off <- mean(E(blackcod.graph.directed)$weight)
cv.cut.off <- mean(E(blackcod.graph.directed)$cv[E(blackcod.graph.directed)$cv > 0])
#graph.sp <- delete_edges(graph, E(graph)[weight < cut.off])

png(filename="../../figs/network-all-regions.png", width=800, height=800)
blackcod.graph.directed.minimal <- delete.edges(blackcod.graph.directed, E(blackcod.graph.directed)[cv > cv.cut.off])
blackcod.graph.directed.minimal <- delete.edges(blackcod.graph.directed.minimal, E(blackcod.graph.directed.minimal)[weight < mean.cut.off])
plot(wc,blackcod.graph.directed.minimal, edge.arrow.size=1, edge.curved=0.1, edge.width=E(blackcod.graph.directed.minimal)$weight/500, vertex.label.family="Helvetica", vertex.label.color="black", vertex.label.cex=1.5, vertex.label=region.names, vertex.label.dist=2, vertex.size=5, layout=layout_in_circle)
dev.off()

p1 <- ggdraw() + draw_image("../../figs/dendo-all-regions.png")
p2 <- ggdraw()+ draw_image("../../figs/network-all-regions.png")
grid <- plot_grid(p1,p2, labels="AUTO", align="v", nrow=2, ncol=1)
save_plot("../../figs/graph-all.png", grid, nrow=2, ncol=1, base_aspect_ratio = 1.1)
```

```{r}
regions.data.graph.known <- regions.data.graph %>% filter(source.region == 'NSW05' | source.region == 'NSW06' | source.region == 'NSW09' | source.region == 'NSW18' | source.region == 'NSW19') %>% filter(settle.region == 'NSW05' | settle.region == 'NSW06' | settle.region == 'NSW09' | settle.region == 'NSW18' | settle.region == 'NSW19')



blackcod.graph.directed.known <- graph_from_data_frame(regions.data.graph.known, directed=TRUE)
wc.known <- walktrap.community(blackcod.graph.directed.known)
png(filename="../../figs/dendo-known-regions.png", width=800, height=800)
plot_dendrogram(wc.known, mode="hclust", label=region.names.known, cex=1.5, palette=c("mediumpurple","tomato"))
dev.off()


#graph.sp <- delete_edges(graph, E(graph)[weight < cut.off])
blackcod.graph.directed.known <- igraph::simplify(blackcod.graph.directed.known, remove.multiple = FALSE, remove.loops=TRUE)
mean.cut.off.known <- mean(E(blackcod.graph.directed.known)$weight)
cv.cut.off.known <- mean(E(blackcod.graph.directed.known)$cv[E(blackcod.graph.directed.known)$cv > 0])
blackcod.graph.directed.known.minimal <- igraph::delete.edges(blackcod.graph.directed.known, E(blackcod.graph.directed.known)[cv > cv.cut.off.known])
blackcod.graph.directed.known.minimal <- delete.edges(blackcod.graph.directed.known.minimal, E(blackcod.graph.directed.known.minimal)[weight < mean.cut.off.known])
png(filename="../../figs/network-known-regions.png", width=800, height=800)
plot(wc.known,blackcod.graph.directed.known.minimal, edge.arrow.size=1, edge.curved=0.1, edge.width=E(blackcod.graph.directed.known.minimal)$weight/500, vertex.label.family="Helvetica", vertex.label = region.names.known, vertex.label.color="black", vertex.label.cex=1.5, vertex.label.dist=2, vertex.size=5, layout=layout_in_circle)
dev.off()

p1 <- ggdraw() + draw_image("../../figs/dendo-known-regions.png")
p2 <- ggdraw()+ draw_image("../../figs/network-known-regions.png")
grid <- plot_grid(p1,p2, labels="AUTO", align="v", nrow=2, ncol=1)
save_plot("../../figs/graph-known.png", grid, nrow=2, ncol=1, base_aspect_ratio = 1.1)

```

Hubs and Authorities
```{r}

as <- authority_score(blackcod.graph)$vector
hs <- hub_score(blackcod.graph)$vector
par(mfrow=c(1,2))
plot(blackcod.graph, vertex.size = as*50, edge.arrow.size=0.1,edge.curved=0.1,vertex.label=region.names, main="Links out", vertex.label.family="Helvetica", vertex.label.color="black", vertex.label.cex=0.7)
plot(blackcod.graph, vertex.size = hs*50, edge.arrow.size=0.1, edge.curved=0.1,vertex.label=region.names,main="Links in", vertex.label.family="Helvetica", vertex.label.color="black", vertex.label.cex=0.7)
```


```{r}
graph.net <- graph
V(graph.net)$size <- 8
V(graph.net)$frame.color <- "white"
V(graph.net)$color <- "orange"
V(graph.net)$label =""
E(graph.net)$arrow.mode <- 0
plot(graph.net, layout=layout_with_lgl)
```

Sparsify the graph
```{r}
cut.off <- mean(E(graph)$weight)
par(mfrow=c(1,2))
graph.sp <- delete_edges(graph, E(graph)[weight < cut.off])
plot(graph.sp, edge.arrow.size=0.2, edge.curved=0.1, edge.width=E(graph)$weight/500, vertex.label.family="Helvetica", vertex.label.color="gray40", vertex.label.cex=0.9,vertex.label=region.names, vertex.label.font=2, vertex.shape="none",main="Strong")
graph.sp <- delete_edges(graph, E(graph)[weight < cut.off])
plot(graph.sp, edge.arrow.size=0.2, edge.curved=0.1, edge.width=E(graph)$weight/500, vertex.label.family="Helvetica", vertex.label.color="gray40", vertex.label.cex=0.9,vertex.label=region.names, vertex.label.font=2, vertex.shape="none",main="Weak")
```

```{r}
graph.m <- get.adjacency(graph, attr="weight", sparse = FALSE)
colnames(graph.m) <- region.names
rownames(graph.m) <- region.names
palf <- colorRampPalette(c("gold","dark orange"))
heatmap(graph.m, Rowv=NA, Colv=NA, col=palf(100), scale="col", margins=c(10,10))

```

```{r}
deg <- degree(graph, mode="all")
deg.dist <- degree_distribution(graph, cumulative=TRUE, mode="all")
plot( x=0:max(deg), y=1-deg.dist,pch=19, cex=1.2, col="orange", xlab="Degree", ylab="Freq")
```

```{r}
mpas <- incident_edges(graph, c(2,5,9,18,13,19,7,10,11), mode = "all")
ecol <- rep("gray80", ecount(graph))
ecol[mpas$NSW02] <- "orange"
ecol[mpas$NSW05] <- "orange"
ecol[mpas$NSW09] <- "orange"
ecol[mpas$NSW18] <- "orange"
ecol[mpas$NSW13] <- "orange"
ecol[mpas$NSW19] <- "orange"
ecol[mpas$NSW07] <- "orange"
ecol[mpas$NSW10] <- "orange"
ecol[mpas$NSW11] <- "orange"
vcol <- rep("grey80", vcount(graph))
vcol[c(2,5,9,18,13,19,7,10,11)] <- "gold"
plot(simplify(graph), vertex.color=vcol, edge.color=ecol, edge.arrow.size=0.2, edge.curved=0.1, edge.width=E(graph)$weight/500, vertex.label.family="Helvetica", vertex.label.color="black", vertex.label.cex=0.9,vertex.label=region.names, vertex.label.font=2, main="MPAs", layout=layout_in_circle)

par(mfrow=c(1,2))
plot(graph.simple, vertex.color=vcol, edge.color=ecol, vertex.size = as*50, edge.arrow.size=0.1,edge.curved=0.1,vertex.label=region.names, main="Links out", vertex.label.family="Helvetica", vertex.label.color="black", vertex.label.cex=0.7)
plot(graph, vertex.color=vcol, edge.color=ecol, vertex.size = hs*50, edge.arrow.size=0.1, edge.curved=0.1,vertex.label=region.names,main="Links in", vertex.label.family="Helvetica", vertex.label.color="black", vertex.label.cex=0.7)

```

Community detection
```{r}

ceb <- cluster_edge_betweenness(blackcod.graph.undirected)
dendPlot(ceb, mode="hclust", label=region.names, color=c("purple","red","green","blue"))
plot(ceb, blackcod.graph, vertex.size = as*50, edge.arrow.size=0.1, edge.curved=0.1, vertex.label.family="Helvetica", vertex.label.color="black", vertex.label.cex=1.5,vertex.label=region.names)

clp <- cluster_fast_greedy(as.undirected(blackcod.graph.undirected))

sg <- spinglass.community(graph)
graph5 <- qgraph(cormatrix, graph="glasso", layout="spring", sampleSize = nrow(data),groups=group.spinglass, 
                 vsize=7, cut=0, maximum=.45, border.width=1.5,
                 color=c("red", "orange", "white", "blue", "green"), title="igraph spinglass")
layout <-layout.fruchterman.reingold(graph)
new_cols <- c("white", "red", "black")[membership(sg)]
plot(sg, graph, col=new_cols, mark.border="black", mark.col=c("tan", "pink", "lightgray"), 
    layout=layout, vertex.label=NA, vertex.size=5, edge.arrow.size=.2)

dhc <- as.dendrogram(clp)
# Rectangular lines
ddata <- dendro_data(dhc, type = "rectangle")
p <- ggplot(segment(ddata)) + 
  geom_segment(aes(x = x, y = label, xend = xend, yend = yend)) + 
  coord_flip() + 
  scale_y_reverse(expand = c(0.2, 0))
p

plot(clp, as.undirected(graph), edge.arrow.size=0.1, edge.curved=0.1, vertex.label.family="Helvetica", vertex.label.color="black", vertex.label.cex=0.7,vertex.label=region.names)

V(graph)$community <- sg$membership
clrs <- adjustcolor(c("tomato","gold","yellowgreen","blue","brown"), alpha=0.5)
plot(graph, vertex.color=clrs[V(graph)$community],edge.arrow.size=0.2, edge.curved=0.1, edge.width=E(graph)$weight/1000,vertex.label.family="Helvetica", vertex.label.color="black", vertex.label.cex=0.7,vertex.label=region.names, layout=layout)
```

```{r}
graph.indicies <- GenInd(get.adjacency(graph, sparse=FALSE))
graph()
```

