java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive-surface/passive-surf-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive-surface/passive-surf-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive-surface/passive-surf-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive-surface/passive-surf-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive-surface/passive-surf-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive-surface/passive-surf-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive-surface/passive-surf-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive-surface/passive-surf-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive-surface/passive-surf-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive-surface/passive-surf-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive-surface/passive-surf-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive-surface/passive-surf-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive-surface/passive-surf-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive-surface/passive-surf-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive-surface/passive-surf-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive-surface/passive-surf-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive-surface/passive-surf-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate-surface/orientate-surf-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate-surface/orientate-surf-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate-surface/orientate-surf-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate-surface/orientate-surf-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate-surface/orientate-surf-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate-surface/orientate-surf-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate-surface/orientate-surf-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate-surface/orientate-surf-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate-surface/orientate-surf-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate-surface/orientate-surf-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate-surface/orientate-surf-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate-surface/orientate-surf-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate-surface/orientate-surf-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate-surface/orientate-surf-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate-surface/orientate-surf-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate-surface/orientate-surf-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate-surface/orientate-surf-nsw17.xml
