java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw01.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw02.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw03.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw04.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw05.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw06.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw07.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw08.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw09.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw10.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw11.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw12.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw13.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw14.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw15.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw16.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw17.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw01.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw02.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw03.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw04.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw05.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw06.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw07.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw08.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw09.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw10.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw11.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw12.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw13.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw14.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw15.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw16.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw17.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw01.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw02.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw03.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw04.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw05.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw06.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw07.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw08.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw09.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw10.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw11.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw12.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw13.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw14.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw15.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw16.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw17.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw01.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw02.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw03.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw04.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw05.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw06.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw07.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw08.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw09.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw10.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw11.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw12.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw13.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw14.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw15.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw16.xml
java -Xmx8g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw17.xml
