java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw17.xml
