java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive/passive-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive/passive-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive/passive-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive/passive-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive/passive-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive/passive-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive/passive-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive/passive-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive/passive-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive/passive-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive/passive-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive/passive-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive/passive-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive/passive-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive/passive-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive/passive-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/passive/passive-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel/diel-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel/diel-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel/diel-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel/diel-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel/diel-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel/diel-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel/diel-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel/diel-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel/diel-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel/diel-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel/diel-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel/diel-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel/diel-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel/diel-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel/diel-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel/diel-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel/diel-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm/ovm-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm/ovm-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm/ovm-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm/ovm-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm/ovm-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm/ovm-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm/ovm-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm/ovm-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm/ovm-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm/ovm-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm/ovm-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm/ovm-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm/ovm-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm/ovm-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm/ovm-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm/ovm-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm/ovm-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate/orientate-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate/orientate-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate/orientate-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate/orientate-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate/orientate-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate/orientate-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate/orientate-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate/orientate-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate/orientate-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate/orientate-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate/orientate-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate/orientate-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate/orientate-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate/orientate-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate/orientate-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate/orientate-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/orientate/orientate-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm/diel-ovm-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-orientate/diel-orientate-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/diel-ovm-orientate/diel-ovm-orientate-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-orientate/ovm-orientate-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-labrid/ovm-labrid-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-mullid/ovm-mullid-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scorp/ovm-scorp-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-serranid/ovm-serranid-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-synod/ovm-synod-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-scarid/ovm-scarid-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-daily/ovm-daily-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-daily/ovm-daily-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-daily/ovm-daily-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-daily/ovm-daily-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-daily/ovm-daily-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-daily/ovm-daily-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-daily/ovm-daily-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-daily/ovm-daily-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-daily/ovm-daily-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-daily/ovm-daily-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-daily/ovm-daily-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-daily/ovm-daily-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-daily/ovm-daily-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-daily/ovm-daily-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-daily/ovm-daily-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-daily/ovm-daily-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-daily/ovm-daily-nsw17.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-timestep/ovm-timestep-nsw01.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-timestep/ovm-timestep-nsw02.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-timestep/ovm-timestep-nsw03.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-timestep/ovm-timestep-nsw04.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-timestep/ovm-timestep-nsw05.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-timestep/ovm-timestep-nsw06.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-timestep/ovm-timestep-nsw07.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-timestep/ovm-timestep-nsw08.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-timestep/ovm-timestep-nsw09.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-timestep/ovm-timestep-nsw10.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-timestep/ovm-timestep-nsw11.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-timestep/ovm-timestep-nsw12.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-timestep/ovm-timestep-nsw13.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-timestep/ovm-timestep-nsw14.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-timestep/ovm-timestep-nsw15.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-timestep/ovm-timestep-nsw16.xml
java -Xms4g -Xmx16g -jar /usr/local/bin/zissou/zissou.jar /srv/zissou/input/config/theoretical/ovm-timestep/ovm-timestep-nsw17.xml
